/**
 * Common type definitions used across Reactor SDK packages.
 */

/**
 * User object returned from auth endpoints.
 */
export interface User {
  id: string;
  email: string;
  email_verified: boolean;
  metadata: Record<string, unknown>;
  created_at: string;
}

/**
 * Session object containing tokens.
 */
export interface Session {
  access_token: string;
  refresh_token: string;
  expires_at: string;
  user: User;
}

/**
 * Organization object.
 */
export interface Organization {
  id: string;
  slug: string;
  name: string;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

/**
 * Organization membership.
 */
export interface Member {
  id: string;
  user_id: string;
  org_id: string;
  role_id: string;
  user: User;
  created_at: string;
  updated_at: string;
}

/**
 * Organization role.
 */
export interface Role {
  id: string;
  name: string;
  description?: string;
  permissions: string[];
  is_default: boolean;
}

/**
 * Organization invitation.
 */
export interface Invitation {
  id: string;
  org_id: string;
  email: string;
  role_id: string;
  status: 'pending' | 'accepted' | 'expired' | 'revoked';
  expires_at: string;
  created_at: string;
}

/**
 * API key.
 */
export interface ApiKey {
  id: string;
  name: string;
  key_prefix: string;
  scopes: string[];
  last_used_at?: string;
  expires_at?: string;
  created_at: string;
}

/**
 * Generic pagination parameters.
 */
export interface PaginationParams {
  limit?: number;
  offset?: number;
}

/**
 * Paginated response wrapper.
 */
export interface PaginatedResponse<T> {
  data: T[];
  total?: number;
  limit: number;
  offset: number;
}

/**
 * Auth state change events.
 */
export type AuthStateEvent =
  | 'INITIAL_SESSION'
  | 'SIGNED_IN'
  | 'SIGNED_OUT'
  | 'TOKEN_REFRESHED'
  | 'USER_UPDATED';

/**
 * Subscription to auth state changes.
 */
export interface AuthStateSubscription {
  unsubscribe: () => void;
}

/**
 * Database type structure for type-safe queries.
 * This is the shape generated by `reactor types generate`.
 */
export interface DatabaseSchema {
  public: {
    Tables: {
      [tableName: string]: {
        Row: Record<string, unknown>;
        Insert: Record<string, unknown>;
        Update: Record<string, unknown>;
        Relationships?: Array<{
          foreignKeyName: string;
          columns: string[];
          referencedRelation: string;
          referencedColumns: string[];
        }>;
      };
    };
    Views?: {
      [viewName: string]: {
        Row: Record<string, unknown>;
      };
    };
    Functions?: {
      [functionName: string]: {
        Args: Record<string, unknown>;
        Returns: unknown;
      };
    };
    Enums?: {
      [enumName: string]: string;
    };
  };
}

/**
 * Generic database schema for when types are not generated.
 */
export type GenericDatabase = DatabaseSchema;

/**
 * Helper to extract table row type.
 */
export type TableRow<
  DB extends DatabaseSchema,
  T extends keyof DB['public']['Tables'],
> = DB['public']['Tables'][T]['Row'];

/**
 * Helper to extract table insert type.
 */
export type TableInsert<
  DB extends DatabaseSchema,
  T extends keyof DB['public']['Tables'],
> = DB['public']['Tables'][T]['Insert'];

/**
 * Helper to extract table update type.
 */
export type TableUpdate<
  DB extends DatabaseSchema,
  T extends keyof DB['public']['Tables'],
> = DB['public']['Tables'][T]['Update'];
