//! Admin endpoints for reactor-data.

use crate::state::DataState;
use crate::store::{DataStore, SchemaSnapshot, TableSnapshot};
use axum::{
    extract::State,
    http::{header, StatusCode},
    response::{IntoResponse, Response},
};

/// The default schema to introspect for user tables.
const USER_SCHEMA: &str = "public";

/// GET /data/v1/_admin/types/typescript
///
/// Generate TypeScript type definitions for the database schema.
/// This endpoint introspects the database schema and generates types
/// matching the Supabase `Database` interface shape.
#[utoipa::path(
    get,
    path = "/data/v1/_admin/types/typescript",
    tag = "data.admin",
    responses(
        (status = 200, description = "TypeScript type definitions", content_type = "text/typescript"),
        (status = 401, description = "Unauthorized"),
        (status = 500, description = "Internal server error"),
    ),
    security(
        ("bearer" = [])
    )
)]
pub async fn generate_typescript<S: DataStore>(
    State(state): State<DataState<S>>,
) -> impl IntoResponse {
    match state.store.introspect_schema(USER_SCHEMA).await {
        Ok(snapshot) => {
            let output = generate_typescript_types(&snapshot);
            Response::builder()
                .status(StatusCode::OK)
                .header(header::CONTENT_TYPE, "text/typescript; charset=utf-8")
                .body(output)
                .unwrap()
        }
        Err(e) => {
            tracing::error!(error = %e, "failed to introspect schema");
            Response::builder()
                .status(StatusCode::INTERNAL_SERVER_ERROR)
                .body("Failed to introspect database schema".to_string())
                .unwrap()
        }
    }
}

/// Generate TypeScript type definitions from introspected tables.
fn generate_typescript_types(snapshot: &SchemaSnapshot) -> String {
    let mut output = String::new();

    // Header
    output.push_str("// Generated by Reactor CLI\n");
    output.push_str("// Do not edit manually\n\n");
    output.push_str("export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[]\n\n");

    // Generate the Database interface
    output.push_str("export interface Database {\n");
    output.push_str("  public: {\n");
    output.push_str("    Tables: {\n");

    // Sort tables for consistent output
    let mut tables: Vec<&TableSnapshot> = snapshot.tables.values().collect();
    tables.sort_by(|a, b| a.name.cmp(&b.name));

    for table in tables {
        output.push_str(&format!("      {}: {{\n", table.name));

        // Row type
        output.push_str("        Row: {\n");
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.sql_type, col.nullable);
            output.push_str(&format!("          {}: {}\n", col.name, ts_type));
        }
        output.push_str("        }\n");

        // Insert type (columns with defaults are optional)
        output.push_str("        Insert: {\n");
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.sql_type, col.nullable);
            let is_pk = table.primary_key.contains(&col.name);
            let optional = col.default.is_some() || is_pk;
            let opt_marker = if optional { "?" } else { "" };
            output.push_str(&format!("          {}{}: {}\n", col.name, opt_marker, ts_type));
        }
        output.push_str("        }\n");

        // Update type (all optional)
        output.push_str("        Update: {\n");
        for col in &table.columns {
            let ts_type = pg_type_to_ts(&col.sql_type, col.nullable);
            output.push_str(&format!("          {}?: {}\n", col.name, ts_type));
        }
        output.push_str("        }\n");

        // Relationships (placeholder)
        output.push_str("        Relationships: []\n");
        output.push_str("      }\n");
    }

    output.push_str("    }\n");
    output.push_str("    Views: {}\n");
    output.push_str("    Functions: {}\n");
    output.push_str("    Enums: {}\n");
    output.push_str("  }\n");
    output.push_str("}\n");

    output
}

/// Convert a PostgreSQL data type to a TypeScript type string.
fn pg_type_to_ts(sql_type: &str, nullable: bool) -> String {
    let type_lower = sql_type.to_lowercase();
    
    // Check for array types first
    if type_lower.ends_with("[]") {
        let element_type = &sql_type[..sql_type.len() - 2];
        let element_ts = pg_type_to_ts_base(element_type);
        let base = format!("{}[]", element_ts);
        return if nullable {
            format!("{} | null", base)
        } else {
            base
        };
    }
    
    let base = pg_type_to_ts_base(&type_lower);
    
    if nullable {
        format!("{} | null", base)
    } else {
        base.to_string()
    }
}

/// Convert a base PostgreSQL type to TypeScript (without null handling).
fn pg_type_to_ts_base(sql_type: &str) -> &'static str {
    match sql_type.to_lowercase().as_str() {
        "uuid" | "reactor_id" => "string",
        "text" | "character varying" | "varchar" | "char" | "character" | "name" | "citext" => "string",
        "boolean" | "bool" => "boolean",
        "smallint" | "integer" | "int" | "int2" | "int4" | "bigint" | "int8" 
        | "serial" | "bigserial" | "smallserial" | "serial4" | "serial8" => "number",
        "real" | "double precision" | "float4" | "float8" | "numeric" | "decimal" | "money" => "number",
        "timestamp without time zone" | "timestamp" | "timestamp with time zone" | "timestamptz" => "string",
        "date" => "string",
        "time" | "time with time zone" | "timetz" | "time without time zone" => "string",
        "interval" => "string",
        "json" | "jsonb" => "Json",
        "bytea" => "string",
        "inet" | "cidr" | "macaddr" | "macaddr8" => "string",
        "point" | "line" | "lseg" | "box" | "path" | "polygon" | "circle" => "unknown",
        "tsvector" | "tsquery" => "string",
        "xml" => "string",
        "oid" => "number",
        _ => "unknown",
    }
}
